from .factory import create_pro_speaker, create_anti_speaker, create_judge, create_moderator
from .prompts import PRO_SPEAKER_INSTRUCTIONS, ANTI_SPEAKER_INSTRUCTIONS, MODERATOR_INSTRUCTIONS, JUDGE_INSTRUCTIONS
from .formatted_prompts import final_verdict_prompt, moderator_prompt, moderator_correction_prompt, speaker_prompt