[project]
name = "ai-debate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritwik Mitra", email = "ritwik.mitra@verse.in" }
]
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.26.0",
    "openai-agents>=0.22.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-debate = "ai_debate:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]